// This file is auto-generated by scripts/generate-client-routes.js
// Do not edit manually - run 'pnpm run generate:routes' to update

import type { Express } from 'express'
import path from 'node:path'

// Static routes precede dynamic routes so exact matches take priority.
const CLIENT_ROUTES = [
  '/',
  '/404',
  '/demo',
  '/dev-settings',
  '/lab',
  '/doc-not-found/:title',
  '/n/:title',
  '/open/:title',
] as const

/** Serve the React SPA for valid client routes only. */
export function registerClientRoutes(app: Express, distPath: string) {
  for (const route of CLIENT_ROUTES) {
    app.get(route, (_req, res) => {
      res.sendFile(path.join(distPath, 'index.html'))
    })
  }
}
