/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrpcTestRouteImport } from './routes/trpc-test'
import { Route as ScratchRouteImport } from './routes/scratch'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpenTitleRouteImport } from './routes/open/$title'
import { Route as NTitleRouteImport } from './routes/n/$title'
import { Route as DocNotFoundTitleRouteImport } from './routes/doc-not-found/$title'

const TrpcTestRoute = TrpcTestRouteImport.update({
  id: '/trpc-test',
  path: '/trpc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchRoute = ScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenTitleRoute = OpenTitleRouteImport.update({
  id: '/open/$title',
  path: '/open/$title',
  getParentRoute: () => rootRouteImport,
} as any)
const NTitleRoute = NTitleRouteImport.update({
  id: '/n/$title',
  path: '/n/$title',
  getParentRoute: () => rootRouteImport,
} as any)
const DocNotFoundTitleRoute = DocNotFoundTitleRouteImport.update({
  id: '/doc-not-found/$title',
  path: '/doc-not-found/$title',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/lab': typeof LabRoute
  '/scratch': typeof ScratchRoute
  '/trpc-test': typeof TrpcTestRoute
  '/doc-not-found/$title': typeof DocNotFoundTitleRoute
  '/n/$title': typeof NTitleRoute
  '/open/$title': typeof OpenTitleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/lab': typeof LabRoute
  '/scratch': typeof ScratchRoute
  '/trpc-test': typeof TrpcTestRoute
  '/doc-not-found/$title': typeof DocNotFoundTitleRoute
  '/n/$title': typeof NTitleRoute
  '/open/$title': typeof OpenTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/lab': typeof LabRoute
  '/scratch': typeof ScratchRoute
  '/trpc-test': typeof TrpcTestRoute
  '/doc-not-found/$title': typeof DocNotFoundTitleRoute
  '/n/$title': typeof NTitleRoute
  '/open/$title': typeof OpenTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/demo'
    | '/dev'
    | '/lab'
    | '/scratch'
    | '/trpc-test'
    | '/doc-not-found/$title'
    | '/n/$title'
    | '/open/$title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/demo'
    | '/dev'
    | '/lab'
    | '/scratch'
    | '/trpc-test'
    | '/doc-not-found/$title'
    | '/n/$title'
    | '/open/$title'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/demo'
    | '/dev'
    | '/lab'
    | '/scratch'
    | '/trpc-test'
    | '/doc-not-found/$title'
    | '/n/$title'
    | '/open/$title'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DemoRoute: typeof DemoRoute
  DevRoute: typeof DevRoute
  LabRoute: typeof LabRoute
  ScratchRoute: typeof ScratchRoute
  TrpcTestRoute: typeof TrpcTestRoute
  DocNotFoundTitleRoute: typeof DocNotFoundTitleRoute
  NTitleRoute: typeof NTitleRoute
  OpenTitleRoute: typeof OpenTitleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trpc-test': {
      id: '/trpc-test'
      path: '/trpc-test'
      fullPath: '/trpc-test'
      preLoaderRoute: typeof TrpcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratch': {
      id: '/scratch'
      path: '/scratch'
      fullPath: '/scratch'
      preLoaderRoute: typeof ScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/$title': {
      id: '/open/$title'
      path: '/open/$title'
      fullPath: '/open/$title'
      preLoaderRoute: typeof OpenTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$title': {
      id: '/n/$title'
      path: '/n/$title'
      fullPath: '/n/$title'
      preLoaderRoute: typeof NTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc-not-found/$title': {
      id: '/doc-not-found/$title'
      path: '/doc-not-found/$title'
      fullPath: '/doc-not-found/$title'
      preLoaderRoute: typeof DocNotFoundTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DemoRoute: DemoRoute,
  DevRoute: DevRoute,
  LabRoute: LabRoute,
  ScratchRoute: ScratchRoute,
  TrpcTestRoute: TrpcTestRoute,
  DocNotFoundTitleRoute: DocNotFoundTitleRoute,
  NTitleRoute: NTitleRoute,
  OpenTitleRoute: OpenTitleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
