name: Check

on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browser
        run: pnpm exec playwright install --with-deps chromium

      # tsc --noEmit && eslint . && prettier --check .
      - name: Check types, lint and formatting
        run: pnpm check

      - name: Run tests
        run: pnpm test
